### ISSUE TITLE
Point_distance_matrix

### ISSUE THREAD

**Issue by kuvshinovdr** [kuvshinovdr/OGxx#13]
Создать файл point_distance_matrix.cpp.
В нём определить класс ogxx::Point_distance_matrix: public ogxx::St_matrix\<ogxx::Float\>, который будет хранить vector\<vector\<ogxx::Float\>\> -- вектор точек, заданных векторами координат.
Данный класс предполагает только const-методы (матрица вычисляется по запросу). Матрица квадратная размера равного числу точек. Расстояния вычисляются с помощью следующих метрик (фиксированный набор вариантов):
* метрика-0 (расстояние Хэмминга): количество несовпадающих координат;
* метрика-1 (Манхэттен): сумма модулей разностей;
* метрика-2: евклидово расстояние;
* метрика-бесконечность (расстояние Чебышёва): максимум из модулей разностей координат;
* французская железнодорожная метрика: если прямая, проведённая через точки, проходит через начало СК, то это евклидово расстояние между этими точками, иначе -- это сумма евклидовых расстояний от начала СК до каждой из точек.

Данному классу нужен будет интерфейс, позволяющий задавать точки и переключать выбранную метрику.

**Comment by Alexanders2007** [comment]
Здравствуйте. Задание выполнено (см. коммит point_distance_matrix.cpp). Отправлено из приложения "Почта" для Windows От: Dmitry R. KuvshinovОтправлено: 21 октября 2023 г. в 22:57Кому: kuvshinovdr/OGxxКопия: Alexander Sutyagin (Александр Сутягин); AssignТема: [kuvshinovdr/OGxx] Point_distance_matrix (Issue #13) Создать файл point_distance_matrix.cpp.В нём определить класс ogxx::Point_distance_matrix: public ogxx::St_matrix<ogxx::Float>, который будет хранить vector<vector<ogxx::Float>> -- вектор точек, заданных векторами координат.Данный класс предполагает только const-методы (матрица вычисляется по запросу). Матрица квадратная размера равного числу точек. Расстояния вычисляются с помощью следующих метрик (фиксированный набор вариантов):метрика-0 (расстояние Хэмминга): количество несовпадающих координат;метрика-1 (Манхэттен): сумма модулей разностей;метрика-2: евклидово расстояние;метрика-бесконечность (расстояние Чебышёва): максимум из модулей разностей координат;французская железнодорожная метрика: если прямая, проведённая через точки, проходит через начало СК, то это евклидово расстояние между этими точками, иначе -- это сумма евклидовых расстояний от начала СК до каждой из точек.Данному классу нужен будет интерфейс, позволяющий задавать точки и переключать выбранную метрику.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by kuvshinovdr** [comment]
А вы сделали push? Пока ничего нет.

**Comment by Alexanders2007** [comment]
Да, сделал. В своей ветке.

пн, 23 окт. 2023 г., 22:51 Dmitry R. Kuvshinov ***@***.***>:

**Comment by kuvshinovdr** [comment]
Теперь вижу.

1. Переместите файл в source.
2. В начале файла должен быть документирующий комментарий с тегами @file, @brief, @author.
3. Не дублируйте определение St_matrix, надо подключить ogxx/st_matrix.hpp.
4. При вычислении метрик надо учитывать, что размерности вложенных векторов могут быть разными: если в одном векторе меньше координат, чем в другом, то следует вычислять метрику так, будто он дополнен нулями.
5. french_railway_distance не проверяет коллинеарность.

**Comment by Alexanders2007** [comment]
Пункты 1-2 исправлены под коммитом point_distance_matrix.cpp_v2

**Comment by kuvshinovdr** [comment]
В v3 вы почему-то заменили то, что делали на совершенно нерелевантный код: решение задачи из предыдущего семестра.

**Comment by kuvshinovdr** [comment]
Кстати, можно было бы сделать более ОО-решение, если отделить метрику от Point_distance_matrix в отдельные классы (для каждой метрики -- свой), спрятанные за общим интерфейсом типа:
interface Metric_compute
{
  Float compute(Float_iterator_uptr first_vector_coords, Float_iterator_uptr second_vector_coords);
};

**Comment by Alexanders2007** [comment]
Замечания исправлены в версии v4, interface Metric_compute реализован в виде класса с подклассами.

**Comment by kuvshinovdr** [comment]
А как насчёт включения интерфейса St_matrix, а не определения своего, и реализации всех его константных методов?

**Comment by Alexanders2007** [comment]
> А как насчёт включения интерфейса St_matrix, а не определения своего, и реализации всех его константных методов?

Имеете ввиду подключение St_matrix.hpp?

**Comment by kuvshinovdr** [comment]
Обновите локальный репозиторий. Я исправил некоторые технические недочёты (можете посмотреть дифф).
1. Размеры векторов могут не совпадать, тогда вычисляем так, будто более короткий дополнен нулями.
2. Железнодорожная метрика должна проверять коллинеарность (расстояние между коллинеарными считается как евклидово).
3. Point_distance_matrix пока не реализует актуальный интерфейс St_matrix (требуется только const-часть).
